#ifndef TMC_EXECUTABLE_RAMP_PLANNER_H
#define TMC_EXECUTABLE_RAMP_PLANNER_H

#include <Arduino.h>

#include "TmcRampCommand.h"
#include "FlowConstraintModel.h"
#include "PlungerMotionPlanner.h"

// ============================================================
// TmcExecutableRampPlanner
// ============================================================
//
// Purpose:
// Convert the ideal fluid-safe curve generated by PlungerMotionPlanner
// into a TMC internal-ramp executable command.
//
// Role boundary:
// - PlungerMotionPlanner:
//     ideal 7-segment reference curve, prediction, duration, preview
//
// - TmcExecutableRampPlanner:
//     TMC-executable ramp parameters:
//       max velocity
//       acceleration
//       deceleration
//       start velocity
//       stop velocity
//       first velocity
//       first acceleration
//       first deceleration
//
// - MotorControlScreen:
//     actually writes the parameters to the TMC driver
//
// Important:
// This planner must not create a separate low-viscosity path.
// Viscosity only affects ramp constraints and parameter strategy.
// ============================================================

class TmcExecutableRampPlanner {
public:
    struct Config {
        // -------------------------
        // Hard lower bounds
        // -------------------------
        float min_velocity_mm_s;
        float min_acceleration_mm_s2;
        float min_deceleration_mm_s2;

        // -------------------------
        // Hard upper bounds
        // -------------------------
        // These are engineering constants, not normal user parameters.
        // They prevent overly aggressive TMC ramps.
        float max_acceleration_mm_s2;
        float max_deceleration_mm_s2;

        // -------------------------
        // Default ramp shape
        // -------------------------
        float start_velocity_mm_s;
        float stop_velocity_mm_s;

        // first_velocity is the initial transition velocity used by
        // the TMC ramp generator. It should be lower than max velocity.
        float first_velocity_ratio;

        // first acceleration / deceleration are usually smaller than
        // max acceleration / deceleration to soften startup and stopping.
        float first_acceleration_ratio;
        float first_deceleration_ratio;

        // -------------------------
        // Viscosity-based strategy
        // -------------------------
        // The values below are not path switches.
        // They only scale ramp aggressiveness.
        float low_viscosity_mPa_s;
        float high_viscosity_mPa_s;

        float low_viscosity_accel_scale;
        float medium_viscosity_accel_scale;
        float high_viscosity_accel_scale;

        // -------------------------
        // Safety
        // -------------------------
        // Additional cap to avoid using exactly 100% of physical limit.
        float velocity_safety_scale;

        // -------------------------
        // Direction
        // -------------------------
        // This should match the physical extrusion direction.
        // Set true or false according to the actual mechanism.
        bool reverse_direction;

        Config()
        : min_velocity_mm_s(0.01f),
          min_acceleration_mm_s2(0.01f),
          min_deceleration_mm_s2(0.01f),
          max_acceleration_mm_s2(5.0f),
          max_deceleration_mm_s2(5.0f),
          start_velocity_mm_s(0.0f),
          stop_velocity_mm_s(0.0f),
          first_velocity_ratio(0.5f),
          first_acceleration_ratio(0.40f),
          first_deceleration_ratio(0.40f),
          low_viscosity_mPa_s(100.0f),
          high_viscosity_mPa_s(30000.0f),
          low_viscosity_accel_scale(1.00f),
          medium_viscosity_accel_scale(0.65f),
          high_viscosity_accel_scale(0.35f),
          velocity_safety_scale(1.0f),
          reverse_direction(true)
        {}
    };

    struct Sample {
        float t_s;

        // TMC-executable approximation
        float distance_mm;
        float volume_uL;
        float velocity_mm_s;

        Sample()
        : t_s(0.0f),
          distance_mm(0.0f),
          volume_uL(0.0f),
          velocity_mm_s(0.0f)
        {}
    };

public:
    TmcExecutableRampPlanner();

    bool build(
        const PlungerMotionPlanner& ideal_planner,
        const FlowConstraintModel::Params& flow_params,
        const FlowConstraintModel::Result& flow_result,
        const Config& config = Config()
    );

    bool isValid() const;

    const TmcRampCommand& command() const;

    float totalDuration() const;

    Sample evaluate(float t_s) const;

private:
    static bool is_valid_positive(float x);
    static float min_positive(float a, float b);
    static float select_acceleration_scale(
        float viscosity_mPa_s,
        const Config& config
    );

private:
    bool m_valid;

    TmcRampCommand m_cmd;
    Config m_config;

    // Cached values for evaluate()
    float m_total_duration_s;
    float m_target_distance_mm;
    float m_stroke_per_ml_mm;

    float m_t_accel_s;
    float m_t_const_s;
    float m_t_decel_s;

    float m_v_max_mm_s;
    float m_a_mm_s2;
    float m_d_mm_s2;

    float m_distance_accel_mm;
    float m_distance_const_mm;
    float m_distance_decel_mm;
};

#endif // TMC_EXECUTABLE_RAMP_PLANNER_H